apiVersion: apps/v1
kind : Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "web"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "web"
  template:
    metadata:
      labels:
        project: "roboshop"
        tier: "data"
        app: "web"     
    spec:
      containers:
      - name: web
        image: jagadevops321/web:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: "web"