apiVersion: apps/v1
kind : StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "mongodb"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "mongodb"
  template:
    metadata:
      labels:
        project: "roboshop"
        tier: "data"
        app: "mongodb"     
    spec:
      containers:
      - name: mongodb
        image: jagadevops321/mongodb:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"